on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
        type: string

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Basic Info"
        run:
          echo "$GITHUB_REF"
          echo "$GITHUB_JOB"
          echo "$GITHUB_ACTION"
          echo "$GITHUB_ACTOR"